# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-web-app-ci
  labels:
    app: go-web-app-ci
spec:
  selector:
    app: go-web-app-ci
    type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    type: NodePort
    
